### ISSUE TITLE
com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process '...aapt" finished with non-zero exit value 1

### ISSUE THREAD

**Issue by jamescfli** [dmsl/anyplace#1]
Tried to import the Android project to Android Studio and met the following issue when 'gradle build' the anyplace module.

    :anyplace:processDebugResources FAILED          
              
    FAILURE: Build failed with an exception.
              
    * What went wrong:
    Execution failed for task ':anyplace:processDebugResources'.
    > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/jamesli/Development/adt-bundle-mac-x86_64-20140702/sdk/build-tools/23.0.2/aapt'' finished with non-zero exit value 1
              
    * Try:        
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
              
    BUILD FAILED  
              
    Total time: 15.409 secs

I tried to run gradle with "--stacktrace",  "--info" and "--debug" as suggested and found no more information. Anyone can help? 

Thanks in advance.

**Comment by constambeys** [comment]
Try to export Anyplace from Eclipse using Export/Generate Grandle build files and then import grandle project from android studio
In my opinion the problem is that the android-support-v4.jar is used by library and ActionBarSherlock projects. I don't know how to fix this in Android Studio. A way around is to remove ActionBarSherlock and android-support-v4.jar and use a repository link.
