### ISSUE TITLE
Best Practices for producing WiFi Radiomap

### ISSUE THREAD

**Issue by zuphilip** [dmsl/anyplace#10]
Any best practice about how to produce an optimal WiFi radiomap would very much be appreciated. It seems that some mobile devices are not working equally good. Can you explain more what "4-directional WiFi acquisition" is?

**Comment by laoudias** [comment]
The best practice to produce an optimal WiFi radiomap (in terms of the resulting positioning accuracy) is the so called "point-by-point" data collection where the collectors visit a number of anchor locations (spanning the entire target area, recommended distance between 2 neighboring locations: 2-3m ) and collect N WiFi RSS samples (fingerprints) in H directions/headings (recommended: at least 4 directions i.e., North/South/East/West) for a total of NxH fingerprints for each anchor location. By averaging the samples in the same direction you can get one fingerprint in each direction. Having fingerprints in several directions increases accuracy because RSS values are affected by the user's body and the smartphone's antenna orientation. This approach, followed in our predecessor Airplace system (https://github.com/dmsl/airplace), produces an optimal WiFi radiomap in terms of the resulting positioning accuracy because the entire area is densely covered, but is very tedious and time consuming.

To address this limitation, Anyplace Logger follows a different approach where the collectors walk along straight paths, clicking on the map to indicate the turning points, until the target area is covered. The fingerprints are automatically location-tagged by intelligently distributing them along each line path (e.g., if the collector pauses for some time in the middle of the segment, then all collected fingerprints during pause time are aggregated to a single fingerprint and tagged with that location) by using the start and end point of each path segment (the assumption is that the collector walks with constant speed between start/pause/end points in the segment). These fingerprints also contain direction/heading information taken from the digital compass reading. These are quantized in four directions implicitly when stored in the radiomap.

This logging process is more intuitive and convenient, but in general generates radiomaps that lead to lower positioning accuracy. This is because some parts of the area may not be adequately covered during data collection, especially if the smartphone's sampling rate is low.

Here are some good practices to produce quality radiomap with Anyplace Logger:
1) Walk along all paths to cover the target area
2) Walk each path at least twice to produce fingerprints in more than one directions (e.g., from left to right and the other way round)
3) If a device has low sampling rate either walk at slower pace while collecting data with the Logger or involve more collectors to cover the same paths multiple times (recommended)

You can always check the density of the collected fingerprints is the Architect and identify gray (low density) or black (no fingerprints) area and guide the collectors.

**Comment by zuphilip** [comment]
Thank you for these detailed information. I have to study and test more how we can perform a WiFi map here. Maybe, your information here would fit as a wiki page: https://github.com/dmsl/anyplace/wiki or some other (more permanent) place for documentation and best practices?

**Comment by dzeina** [comment]
That's a great suggestion. I've transferred Christos' answer to a wiki page.

D.
