### ISSUE TITLE
ARCHITECT-WIFI MAPS

### ISSUE THREAD

**Issue by angenieux** [dmsl/anyplace#16]
Dear All, Great Job !
Just one question.
Is it possible to completly erase the wifi map on a Floor without deleting the complete Floor (POI and itinary...)
Use case: I have uploaded a bad record wifi log (with mistakes) and i would like to make another fingerprinting. Is it possible to renew the wifimap ?

Best regards

**Comment by kgeorgiou** [comment]
Hello @angenieux, 

At the moment there is no graphical user interface in the Architect to support the aforementioned functionality. However, we acknowledge the need of implementing such a feature as soon as possible in order to handle use cases like the one you provided.

For the time being, please send an email to anyplace@cs.ucy.ac.cy with the building and floor you wish for some (or all) of the Wi-Fi fingerprints to be cleared and the team will get on to it as soon as possible.

Thank you for the feedback!

**Comment by anyplaceucy** [comment]
Please reopen if issue persists.
