### ISSUE TITLE
Maps problem

### ISSUE THREAD

**Issue by benmomo** [dmsl/anyplace#166]
I'm trying to get familiar with AnyPlace and test it. I have already uploaded the maps from my university (UPV in Valencia) via the Architect service.

   a) With the desktop browser (Chrome) I can see the 4 floor maps there and everything seems correct.

   b) However, in the mobile app it seems that old versions of the building are being displayed. The new one has 4 floors; the old building has only 2 floors and one is not well positioned. There are also some POIs that are not well positioned.  I have deleted caches and refreshed the building but nothing changes.  I cannot see these old maps in the desktop so I cannot delete them.

I have made the building floors public and tested on the mobile phone of a friend and it still loads the old floor plans. Any idea what is happening there ? The location of the building is (39.479462, -0.342693), in case it helps

**Comment by Costantinos** [comment]
Hello,
It seems that there are two buildings with the following names Teleco UPV and ETSIT at the same location. Do you want me to delete one of them? 

The POIs misplacement is a known issue that will be fixed in the future.
A quick workaround is the following:
•	Zoom to the lowest level on the map in ARCHITECT (Make sure you DON'T use Satellite view as this mode won't allow you to go to the lowest zoom level.)
•	Re-upload the Image floor map. If the image is too big for you to position, consider chopping the image into several images and create 1 building per image.
•	Go to Android and reload the building (through settings).
The above will fix the problem!

**Comment by benmomo** [comment]
'Teleco UPV' is the old building one and should be deleted:
-  I suppose this will automattically delete the POIs there
- The mobile app only shows 'Teleco UPV' as possible building. ETSIT does not appear in the select.

**Comment by Costantinos** [comment]
I have deleted the 'Teleco UPV' and I have checked it on the android application as well. Could you please  refresh buildings and remove the caches form the application. In order to fix the building image you need to follow the steps on the previous message. Could you please verify that this fixed the issue?

**Comment by benmomo** [comment]
Thank you! I was able to insert one floor map, but it is really difficult and unfriendly working with maximum zoom where the whole floor does not fit in the screen. Chopping the image is also an unpleasant workaround, as there is onle 1 building in reality, not 2 or more depending on the size

**Comment by Costantinos** [comment]
I am glad to hear that your issue was resolved. We will improve the process for creating/adding buildings in the future.

**Comment by anyplaceucy** [comment]
If you open the building on a screen with higher resolution you would get a better chance of placing the building correctly.
