### ISSUE TITLE
Ble RadioMap or Wifimap

### ISSUE THREAD

**Issue by enyachoke** [dmsl/anyplace#219]
I have been really wanting to do something on indoor position and I think anyplace is a good starting point. I have some estimote beacons lying around and after a quick scan through the project I believe I could replace the wifimap with blemap or at least addon ble support since the beacons have a unique identifiers that can replace the Bssid and use the beacon rssi as the rss. Does this sound workable or there is more to it.

**Comment by anyplaceucy** [comment]
Your plan makes sense, so please try it and report how well it works!

Let me just mention that in the near future (release 3.5) you can expect a significant amount of API calls for the Wi-Fi Fingerprints. This will be particularly beneficial for Wi-Fi IoT device integration as we will be enabling server-side localization through the JSON API (besides terminal-based localization currently only supported in Android). v3.5 should be expected around Easter time.

In v4.0 we will more on specialized methods for IoT device localization (e.g., BLE and Magentic localization algorithms) besides Wi-Fi localization. This would require separate measurement buckets on our service so that we don't mix apples with oranges. But there is no strict timeplan for v4.0 as of now.

The suggestion is to start collecting data with v3.2 and exploit the whatever WiFi RSS data you collect (from Android or IoT) with v3.5.
