### ISSUE TITLE
Need GPS with Logger?

### ISSUE THREAD

**Issue by Jane-Woodard** [dmsl/anyplace#24]
I have the Google Pixel, which does not have the GPS chip.  Before I can "Start WiFi Recording" it says I must enable GPS.  Isn't this "GPS-less"?

**Comment by constambeys** [comment]
Check the new version v2.3.4

**Comment by Jane-Woodard** [comment]
Thank you!  That worked.  However, now there are two maps showing on the logger.  Neither one is over the building as it is displayed in the architect.  One is smaller than the other.  How do I get the map to overlay the building correctly, as it is in architect, and then how do I remove the logging that I started?  Anyplace is fabulous, and I am excited about getting it operational here.
Thanks!

![logger](https://cloud.githubusercontent.com/assets/19594545/15591975/77977b08-235d-11e6-8006-92a0cced292f.JPG)
![architect](https://cloud.githubusercontent.com/assets/19594545/15591976/779b1a6a-235d-11e6-8c7a-b67013e2a419.jpg)

**Comment by anyplaceucy** [comment]
This is a known problem that will be fixed in the future.

A quick workaround is the following:

Zoom to the lowest level on the map in ARCHITECT (Make sure you DON'T use Satellite view as this mode won't allow you to go to the lowest zoom level.)
Re-upload the Image floor map. If the image is too big for you to position, consider chopping the image into several images and create 1 building per image.
Go to Android and reload the building (through settings).
The above will fix the problem!
