### ISSUE TITLE
Markers in map (viewer) are displayed wrong

### ISSUE THREAD

**Issue by zuphilip** [dmsl/anyplace#3]
It looks for me that the markers in the map are displayed at some wrong positions, e.g.

![anyplace1](https://cloud.githubusercontent.com/assets/5199995/12492636/79590144-c081-11e5-85e1-926a24e9a27c.jpg)

Moreover, the offset (mainly in the horizontal direction) seems to be constant and not changing when zoomed in or out, cf.

![anyplace2](https://cloud.githubusercontent.com/assets/5199995/12492666/9d49c732-c081-11e5-9b6f-00855520cecf.jpg)

**Comment by kgeorgiou** [comment]
Hello @zuphilip 

Do you mind if I ask which browser is used in the above screenshots? There is a known sizing problem for the markers on Firefox, which we are trying to resolve asap. On Chrome they should be showing accurately. 

Let me know if that's the case.

Cheers.

**Comment by zuphilip** [comment]
Yes, indeed. I used Firefox for these screenshots. With chrome it seems to be accurate and also in Edge, which I just tested on your viewer page. I am looking forward for the firefox-fix.

**Comment by zuphilip** [comment]
@kgeorgiou Another browser problem: If we create a new building in the `architect` with chrome then it will display wrong in the app (however it is displayed okay in the `viewer`). Is this also a known problem?

**Comment by jlbalboa** [comment]
Hello @zuphilip and @kgeorgiou .

I am Proffesor on Geomatics at the University of Jaén. A group of students about Location Based Services are using Anyplace and all have a similar problem with the android app.

The buildings images appear to be ok both in the architect and in the viewer. But in the android app the y are displayed wrong (in scale and location). I show you an example below.
Could you please tell me if there is any fix about this?
We have tried to use the architect both in Chrome and I.E.

Regards.

![screenshot_20160126-091050](https://cloud.githubusercontent.com/assets/16916068/12610966/cc70d808-c4ea-11e5-9abd-5a7c230ec58a.png)
![imagen1](https://cloud.githubusercontent.com/assets/16916068/12610967/ccc95960-c4ea-11e5-92cf-d20c003b7f9d.jpg).

**Comment by dzeina** [comment]
This is a known problem that will be fixed in the future.

A quick workaround is the following:

- Zoom to the lowest level on the map in ARCHITECT (Make sure you DON'T use Satellite view as this mode won't allow you to go to the lowest zoom level.)
- Re-upload the Image floor map. If the image is too big for you to position, consider chopping the image into several images and create 1 building per image.
- Go to Android and reload the building  (through settings).

The above will fix the problem!

**Comment by jlbalboa** [comment]
Thank you @dzeina !
I have just tested it and this solution solves the problem.
Yes, it is a bit more complicated using the more detailed level of the zoom.
I'tell to my students!
Regards.

**Comment by Derek-K** [comment]
@dzeina I just tried your suggestion, by zoom into the lowest level w/o satellite mode, cropped the floor plan, and it still doesn't work. (not to mention I have to redo all the POIs now....)

**Comment by dzeina** [comment]
Just reload the building in navigator and it will show up correctly If the problem persists send your building ID to anyplace@cs.ucy.ac.cy

**Comment by dzeina** [comment]
This shouldn't actually require repositioning the POIS, just trip load the floor map image.

**Comment by Derek-K** [comment]
I just tried again. I went into menu and deleted building cache and
reload.  Still looks the same.

Not sure what's the building ID but if you goto World,  you will see "105
Gibson Center"

Thanks

**Comment by Derek-K** [comment]
I have tried again, but this time I am using JPG instead of PNG and seems
to load correctly.

On Wed, Feb 17, 2016 at 1:41 PM, Demetris Zeinalipour <
notifications@github.com> wrote:

> This shouldn't actually require repositioning the POIS, just trip load the
> floor map image.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmsl/anyplace/issues/3#issuecomment-185342408>.
>



-- 

*No trees were harmed in the sending of this message; however, a large
number of electrons were terribly inconvenienced*

**Comment by axlrnish** [comment]
Thanks, I guess there is a work-around which helped. But was hectic to align a floor plan for a large mall area. 

Anyways, now I am getting into another problem now when I try to do Wi-Fi recording. When I am inside the building with the floor plan loaded, locate a point and try to start wi-fi recording, the app says that I should be at a building or a near a building to record wi-fi. I was inside the building and the app also shows that. Has anyone come across this ?

**Comment by Prajithm** [comment]
We also facing the same issue, while we opening the Architec it is showing the correct place, but when we looking the viewer its showing that map is in some oother place.
In the mobile Application also, after some Zoom only the floor diagram is showing, or else it is blank.

**Comment by anyplaceucy** [comment]
This is a known problem that will be fixed in the future.

A quick workaround is the following:

Zoom to the lowest level on the map in ARCHITECT (Make sure you DON'T use Satellite view as this mode won't allow you to go to the lowest zoom level.)
Re-upload the Image floor map. If the image is too big for you to position, consider chopping the image into several images and create 1 building per image.
Go to Android and reload the building (through settings).
The above will fix the problem!

**Comment by prajithmm** [comment]
We have tried the same, lot of times and as well as we have facing some more challenges. 
Is there any timing for syncing the images from the Architec and mobile app, because , if I upload any floor diagram it is showing after 1 day. There is no way to sync immediately.

Is there anyway to contact you to get more details about this, we are planning to implement this in our campus for the students, and faculty to get the location. So please help us to provide the details.

**Comment by Prajithm** [comment]
We are still facing the issue with the floor location in map viewer. Please help somebody who done...?

**Comment by anyplaceucy** [comment]
You probably didn't purge your cache on the Android phone (through Anyplace settings). Please try again.
