### ISSUE TITLE
stairs and elevators in floors

### ISSUE THREAD

**Issue by GoldenWings** [dmsl/anyplace#33]
are stairs and elevators in floors should be marked as building entrance?

**Comment by kgeorgiou** [comment]
No, unless they are the entry points of the building.

POIs marked as building entrances represent the points of entry from which a person can enter the building. They are a special case of POIs because they are used as the endpoints of the line segments drawn on the map, when a user requests for navigation instructions from his current location (outside of the building) to the building.

Stairs and elevators are most commonly found inside a building, however in some cases where a facility's entry point is an elevator or stairs (e.g. an underground facility,) that POI should be marked as a building entrance.

**Comment by GoldenWings** [comment]
When i try to navigate to any POIs in a floor other than the ground it says no entrance found, Any idea why that happening?

**Comment by constambeys** [comment]
Have you registered a building entrance?

**Comment by GoldenWings** [comment]
Yes i did registered the gates of the building you can have a look.
http://anyplace.cs.ucy.ac.cy/viewer/?buid=building_cc6c953a-9ded-42fb-8c1f-6c697f670fcc_1464986495304

**Comment by constambeys** [comment]
Building and POIs are cached in the android app. If you make any change to the building click Refresh Building or clear application's cache from the android settings

**Comment by GoldenWings** [comment]
I already did that but i think the problem maybe resulted from the fact that the floor numbers are not correct, The building consist of basement, ground, floor 1 and floor 2 but I've numbered them from 0 to 3 instead of -1 to 2, and the building entrance is at ground which is at the moment is floor number one instead of 0, this might be the issue?

**Comment by constambeys** [comment]
You are right the navigation only works if there is an entrance in the current floor if the position is not found. I will fix it as soon as possible

**Comment by GoldenWings** [comment]
thanks please keep me updated in the underlying issue when it is fixed.

another thing can i edit the floor numbers without recreating the floors? i dont want to lose POIs and the radiomap.

thanks.

**Comment by constambeys** [comment]
I have fixed the error message and the navigation path should now go throw the ground floor or any floor which has an entrance poi. Check Anyplace version 2.3.5
