### ISSUE TITLE
Which map mode is efficient

### ISSUE THREAD

**Issue by harshitlalpura** [dmsl/anyplace#36]
Hello.

Google map has 2 map mode satellite and map. if we go to satellite actual building is not coming accurately on the building which has shown in the map mode. Now which mode is right. i think satellite mode shows correct position of building. Please help.

Thanks.

**Comment by kgeorgiou** [comment]
Hello @harshitlalpura,

It's up to you really. Although I would suggest the simple map view instead of the satellite view. The satellite images are usually taken from an angle and that might obstruct the alignment of the floor plan.

**Comment by harshitlalpura** [comment]
Hello @kgeorgiou 

thats not my question.. my question is building on map view is different size than satellite view at the same zoom level 18. and position is also difference.. would that affect positioning ?

**Comment by kgeorgiou** [comment]
Hello again @harshitlalpura. It will not affect the positioning since we position the user always within the boundaries of the floor plan, based on the logging done on said floor plan. 

A misplaced floor plan will result in your position on the floor plan overlay to not exactly match the physical location in respect to the world (e.g. your actual location on google maps,) however you will still be positioned accurately in respect to the surroundings within the floor.

Let me know if I should elaborate further and apologies for the delayed response.
