### ISSUE TITLE
Grunt stuck at the "watch" task

### ISSUE THREAD

**Issue by mogarg** [dmsl/anyplace#41]
Trying to host anyplace locally. However, when i run grunt it gets stuck at the "watch" task.

**Comment by kgeorgiou** [comment]
Hi @mogarg, you can `ctrl + c` to kill the `grunt-watch` process without any complications.

[`grunt-watch`](https://github.com/gruntjs/grunt-contrib-watch) keeps running in order to detect any changes you make in html/css/js files and automatically build the project (essentially dump the processed html/css/js files into the build/ directory).

It's clear that `grunt-watch` is only useful on the development environment and should be omitted from the host/production environment. We should separate the grunt tasks for development and production environment, thanks for pointing that out. For now a `ctrl + c` should do.

**Comment by mogarg** [comment]
Hey @kgeorgiou, that makes sense. 
I guess the status which is represented as "Waiting..." does not convey the complete information.
Anyways, thanks for the prompt reply.
