### ISSUE TITLE
After uploading the images in architect mode, it is getting displayed in different location in Android Application

### ISSUE THREAD

**Issue by dhanlivesinblr** [dmsl/anyplace#68]
After uploading the images in architect mode, it is getting displayed in different location in Android Application, It is getting displayed correctly in viewer but when checking in Anyplace Android application it is showing in different location... How to solve this issue

**Comment by anyplaceucy** [comment]
This is a known problem that will be fixed in the future.

A quick workaround is the following:

Zoom to the lowest level on the map in ARCHITECT (Make sure you DON'T use Satellite view as this mode won't allow you to go to the lowest zoom level.)
Re-upload the Image floor map. If the image is too big for you to position, consider chopping the image into several images and create 1 building per image.
Go to Android and reload the building (through settings).
The above will fix the problem!
