### ISSUE TITLE
inaccuare position.

### ISSUE THREAD

**Issue by kodkafali** [dmsl/anyplace#98]
I want to use your Anyplace Application. But, i am having problems in positioning in AnyPlace application. 
Athough it shows my movement correctly, i does not show my starting point correctly, it shows me walking on an empty field.

Could you please help me for this? 

![floor_plan](https://cloud.githubusercontent.com/assets/11686662/21759105/baf1ef48-d652-11e6-8a3e-72412337e53d.PNG)
![on_android](https://cloud.githubusercontent.com/assets/11686662/21759104/baf1fbf0-d652-11e6-907f-8cce40d59e56.jpg)

**Comment by anyplaceucy** [comment]
This is a known problem that will be fixed in the future.

A quick workaround is the following:

Zoom to the lowest level on the map in ARCHITECT (Make sure you DON'T use Satellite view as this mode won't allow you to go to the lowest zoom level.)
Re-upload the Image floor map. If the image is too big for you to position, consider chopping the image into several images and create 1 building per image.
Go to Android and reload the building (through settings).
The above will fix the problem!

Also check: https://github.com/dmsl/anyplace/issues/68

**Comment by EmrahKK** [comment]
Is this issue fixed? I'am having same problem when using navigator. Floor plan that I've prepared on the architect appears in different position on the navigator.
